-- Generated from wp_ai_export. Run AFTER migrations.
-- 1) Upload files per upload_manifest.txt to Supabase Storage bucket artwork-images
-- 2) Project ref already set: rptwowkkejecvvbfsgkt

-- Optional: clear previous import
-- delete from public.exhibition_gallery_images where exhibition_id in (select id from public.exhibitions where slug like '%-%');

begin;

-- PROJECTS (paintings + artworks pages)
insert into public.projects (id, title_en, title_ro, description_en, description_ro, year, museum, image_url, sort_order) values ('03ae5845-df32-5d8e-aa85-455c5816bb78', '”Looking Within”', '”Looking Within”', '', '', 2024, '', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/projects/Andreea-Gabriela-Tudor-Looking-Within-2024-80x60cm-oil-on-canvas.jpg', 0) on conflict (id) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, image_url=excluded.image_url, sort_order=excluded.sort_order;
insert into public.projects (id, title_en, title_ro, description_en, description_ro, year, museum, image_url, sort_order) values ('9f7c29f8-6fe6-5803-b216-8937fd4ade1e', '”Where does the past live?”', '”Where does the past live?”', '', '', 2025, '', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/projects/Andreea-Gabriela-Tudor-Unde-locuieste-trecutul-2025-100x120cmulei-pe-panza.jpg', 2) on conflict (id) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, image_url=excluded.image_url, sort_order=excluded.sort_order;
insert into public.projects (id, title_en, title_ro, description_en, description_ro, year, museum, image_url, sort_order) values ('eeb5c84a-f850-5934-8e90-92a999a68c8e', 'TUDOR-Andreea-Gabriela-Urmeaza-statia-Parfumul-teior-2023-100x100cm-tehnica-mixta-pe-panza.jpg', 'TUDOR-Andreea-Gabriela-Urmeaza-statia-Parfumul-teior-2023-100x100cm-tehnica-mixta-pe-panza.jpg', '', '', 2023, '', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/projects/TUDOR-Andreea-Gabriela-Urmeaza-statia-Parfumul-teior-2023-100x100cm-tehnica-mixta-pe-panza.jpg', 3) on conflict (id) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, image_url=excluded.image_url, sort_order=excluded.sort_order;
insert into public.projects (id, title_en, title_ro, description_en, description_ro, year, museum, image_url, sort_order) values ('b16d7091-a619-5c75-9b9f-3cd2ad9e0e31', 'X6A9560', 'X6A9560', '', '', null, '', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/projects/X6A9560.jpg', 101) on conflict (id) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, image_url=excluded.image_url, sort_order=excluded.sort_order;
insert into public.projects (id, title_en, title_ro, description_en, description_ro, year, museum, image_url, sort_order) values ('e0915305-0479-5732-91aa-3f0bab332865', 'LEV6987 Enhanced NR', 'LEV6987 Enhanced NR', '', '', null, '', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/projects/LEV6987-Enhanced-NR.jpg', 102) on conflict (id) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, image_url=excluded.image_url, sort_order=excluded.sort_order;

-- EXHIBITIONS
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'acest-spatiu-nu-exista', 'This Space Does Not Exist', 'Acest spațiu nu există', 'Itinerant solo exhibition', 'Itinerant solo exhibition', 'The itinerant exhibition project “This Space Does Not Exist” interrogates concepts such as memory, space, and identity. Pursuing an ostensibly documentary intent, the images are, for the most part, staged constructions that explore the theme of identity in relation to the effects of the passage of time. Thus, the image of the self is constructed in relation to the image of the other—namely, “the family”. The narrative dimension of the works can also be understood from the perspective of the scenography proposed by the artist, who, through various associations of elements—whether photographs, personal objects, or documents—manages in some way to blur the boundaries between the real and the imaginary. The perspective becomes symbolic, distancing itself from the perceived reality.', 'The itinerant exhibition project “This Space Does Not Exist” interrogates concepts such as memory, space, and identity. Pursuing an ostensibly documentary intent, the images are, for the most part, staged constructions that explore the theme of identity in relation to the effects of the passage of time. Thus, the image of the self is constructed in relation to the image of the other—namely, “the family”. The narrative dimension of the works can also be understood from the perspective of the scenography proposed by the artist, who, through various associations of elements—whether photographs, personal objects, or documents—manages in some way to blur the boundaries between the real and the imaginary. The perspective becomes symbolic, distancing itself from the perceived reality.', '2024-10-03', '2024-11-03', '03.10-03.11.2024, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', '03.10-03.11.2024, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-24.jpg', true, 0) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-24.jpg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-24.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/acest-spatiu-nu-exista-2.jpg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/acest-spatiu-nu-exista-2.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040495-copy.jpg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040495-copy.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-12.jpg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-12.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7391-enhanced-nr.jpg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7391-enhanced-nr.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7163-enhanced-nr.jpg', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7163-enhanced-nr.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040479-copy.jpg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040479-copy.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-14.jpg', 7 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-14.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-2.jpg', 8 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-2.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-40.jpg', 9 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-40.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-19.jpg', 10 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-19.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040511-copy-1.jpg', 11 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/a040511-copy-1.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-21.jpg', 12 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/sala-vernisaj-andreea-gabriela-tudor-21.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7375-enhanced-nr.jpg', 13 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/lev7375-enhanced-nr.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-46.jpg', 14 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/acest-spatiu-nu-exista/vernisaj-andreea-gabriela-tudor-46.jpg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', '03.10-03.11.2024, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', '03.10-03.11.2024, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and ev.title_en='03.10-03.11.2024, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', '10-19.01.2025, Casa Artelor, Galați, Romania', '10-19.01.2025, Casa Artelor, Galați, Romania', 1 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and ev.title_en='10-19.01.2025, Casa Artelor, Galați, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select 'f4eaab9d-2e61-5063-99b5-945f2ff70cb8', '01-10.02.2025, Casa Muzeelor, Iași, Romania', '01-10.02.2025, Casa Muzeelor, Iași, Romania', 2 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='f4eaab9d-2e61-5063-99b5-945f2ff70cb8' and ev.title_en='01-10.02.2025, Casa Muzeelor, Iași, Romania');
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'assignment-of-identity-receivables', 'Assignment of Identity Receivables', 'Cesiune de creanțe identitare', 'Solo show', 'Solo show', 'Although it has been grouped around a ubiquitous and personal theme (envisioning identity and its components), revolving around subjects regarding experience, memory and personal history, respectively – their transpositions into visual language, the artistic project <Assignments of identity claims> develops on two semantic complementary aspects: On the one hand, the visual (artistic) approach generating significant content involves a collection of stylistically and methodologically diverse corpora. Through them, Andreea Gabriela Tudor proposes a subjective excursion on her experiences, narratives and sources of inspiration, retrospective from the time frame in which they were made (2020-2022), but also prospective from the point of view of configuring her own artistic discourse. On the other hand, the curatorial approach aims at transferring these personal perspectives to the public, converting and assimilating them into a spectrum of immediate and unfiltered experience, phenomenon through which the identity factor (and by extension, the conceptual content) propagates and multiplies. Consequently, through the very title of the exhibition, the curatorial act presupposes the configuration of a so-called “true artistic jurisprudence”. Although the application of legal terminology to the artistic field may seem ironic (and to some extent, inappropriate), the “Brownian” diversity of current exhibition practices proves an acute need to establish set procedures and doctrines. This exhibition aims to lead by example how one can accomplish such ambitions.

By definition, assignment of receivables is the agreement by which the assignor creditor transmits to the assignee a claim against a third party. The position assumed by the curator (of the assigning creditor), to whom the public (the assigned debtor) owes the exhibition experience is transferred to the assignee (the visual artist), as the rightful owner and holder of the significant receivables. The exhibition “case” in question places the nature of significant claims in a personal identity spectrum – everyday experience, micro-narratives of the past, family experience, aspirations or opinions filtered and transitioned by the works of Andreea Gabriela Tudor. In other words, the expectant nature of the public’s positioning towards the presentation of the artistic act is subject to permanent negotiation, whilst the artistic corpus is being reduced as pretext and context of the identity transfer. The double instantiation and the conceptual contamination resulting from this juxtaposition underline the dialectical status of A.G. Tudor`s artworks, deconstructing the unidirectional artistic significance. The public has the freedom to configure its epistemic scaffolding around the works (validating and extracting value judgments), but it can also challenge, deny or discredit them. Thus, the present exhibition abandons teleological semantics in favor of „open-end meanings”.

The fundamental principle around which the artist builds the exhibition series refers to the experience of loneliness. Each work is generated starting from the premise of the moment of introspection, of the encounter with the self, foreshadowing a kaleidoscope of memories and identities. The characters and attitudes represented are avatars of a well-defined moment set in a personal chronology, transposed as hypothetical projections and artistic meta-discourses. The particular identity, memory and introspective exercise are hidden, adjusted, counterfeited and encrypted in such a way that they are not fundamentally equivalent to the artist`s persona. It rather questions and delimits archetypes and instances of the artist. Such elements of truthfulness (considered concrete and reality-anchors) that connect the visual corpora to the person, history and identity of A.G. Tudor are the photographs found in the work that documents the whole process of creation. Consequently, we deduce that the exhibition acquires Warburgian connotations – a trueBilderatlas Mnemosyne, scaled in accordance with the personal experience and the introspective methodology promoted by the artist. The idea of sequentially presenting the sources (underlined by A.G. Tudor in her personal statement: introspection-sleep-dream-death) is foreshadowed by the method of signage – each work is being placed in a pseudo-alveolus suggested by the architecture of the gallery. Although the experience targeted by the artworks is focused on the idea of close-proximity (or contact) with the intimate space of the artist`s identity (resulted from the way the artist perceives the world), the exhibition experience aims exceed this subjective limitation. Intimacy is clinically dissected and converted, transforming the gallery into a veritable laboratory of induced experiences. By shifting the focal point on the ideational transfer and on the artist-public relational formats, it is reaffirmed that contemporary creation has a prominent dialectical status. This debate fosters the permanent negotiation of meaning, role and functions of art.

Fortunately, art is not like law. If the exhibition experience does not involve relevance, interest, or does not achieve its stated purposes, the opposable third party, the assigned debtor (or the public, more specifically) has alternatives. If the present legal-artistic act does not satisfy the general interest, it can be sanctioned with absolute nullity; if it does not satisfy a particular interest, it may be sanctioned with relative nullity. In art, the adoption of such meanings and identities is not mandatory.', 'Although it has been grouped around a ubiquitous and personal theme (envisioning identity and its components), revolving around subjects regarding experience, memory and personal history, respectively – their transpositions into visual language, the artistic project <Assignments of identity claims> develops on two semantic complementary aspects: On the one hand, the visual (artistic) approach generating significant content involves a collection of stylistically and methodologically diverse corpora. Through them, Andreea Gabriela Tudor proposes a subjective excursion on her experiences, narratives and sources of inspiration, retrospective from the time frame in which they were made (2020-2022), but also prospective from the point of view of configuring her own artistic discourse. On the other hand, the curatorial approach aims at transferring these personal perspectives to the public, converting and assimilating them into a spectrum of immediate and unfiltered experience, phenomenon through which the identity factor (and by extension, the conceptual content) propagates and multiplies. Consequently, through the very title of the exhibition, the curatorial act presupposes the configuration of a so-called “true artistic jurisprudence”. Although the application of legal terminology to the artistic field may seem ironic (and to some extent, inappropriate), the “Brownian” diversity of current exhibition practices proves an acute need to establish set procedures and doctrines. This exhibition aims to lead by example how one can accomplish such ambitions.

By definition, assignment of receivables is the agreement by which the assignor creditor transmits to the assignee a claim against a third party. The position assumed by the curator (of the assigning creditor), to whom the public (the assigned debtor) owes the exhibition experience is transferred to the assignee (the visual artist), as the rightful owner and holder of the significant receivables. The exhibition “case” in question places the nature of significant claims in a personal identity spectrum – everyday experience, micro-narratives of the past, family experience, aspirations or opinions filtered and transitioned by the works of Andreea Gabriela Tudor. In other words, the expectant nature of the public’s positioning towards the presentation of the artistic act is subject to permanent negotiation, whilst the artistic corpus is being reduced as pretext and context of the identity transfer. The double instantiation and the conceptual contamination resulting from this juxtaposition underline the dialectical status of A.G. Tudor`s artworks, deconstructing the unidirectional artistic significance. The public has the freedom to configure its epistemic scaffolding around the works (validating and extracting value judgments), but it can also challenge, deny or discredit them. Thus, the present exhibition abandons teleological semantics in favor of „open-end meanings”.

The fundamental principle around which the artist builds the exhibition series refers to the experience of loneliness. Each work is generated starting from the premise of the moment of introspection, of the encounter with the self, foreshadowing a kaleidoscope of memories and identities. The characters and attitudes represented are avatars of a well-defined moment set in a personal chronology, transposed as hypothetical projections and artistic meta-discourses. The particular identity, memory and introspective exercise are hidden, adjusted, counterfeited and encrypted in such a way that they are not fundamentally equivalent to the artist`s persona. It rather questions and delimits archetypes and instances of the artist. Such elements of truthfulness (considered concrete and reality-anchors) that connect the visual corpora to the person, history and identity of A.G. Tudor are the photographs found in the work that documents the whole process of creation. Consequently, we deduce that the exhibition acquires Warburgian connotations – a trueBilderatlas Mnemosyne, scaled in accordance with the personal experience and the introspective methodology promoted by the artist. The idea of sequentially presenting the sources (underlined by A.G. Tudor in her personal statement: introspection-sleep-dream-death) is foreshadowed by the method of signage – each work is being placed in a pseudo-alveolus suggested by the architecture of the gallery. Although the experience targeted by the artworks is focused on the idea of close-proximity (or contact) with the intimate space of the artist`s identity (resulted from the way the artist perceives the world), the exhibition experience aims exceed this subjective limitation. Intimacy is clinically dissected and converted, transforming the gallery into a veritable laboratory of induced experiences. By shifting the focal point on the ideational transfer and on the artist-public relational formats, it is reaffirmed that contemporary creation has a prominent dialectical status. This debate fosters the permanent negotiation of meaning, role and functions of art.

Fortunately, art is not like law. If the exhibition experience does not involve relevance, interest, or does not achieve its stated purposes, the opposable third party, the assigned debtor (or the public, more specifically) has alternatives. If the present legal-artistic act does not satisfy the general interest, it can be sanctioned with absolute nullity; if it does not satisfy a particular interest, it may be sanctioned with relative nullity. In art, the adoption of such meanings and identities is not mandatory.', null, null, '10-17.06.2022, Serfioti Gallery, Galați, Romania', '10-17.06.2022, Serfioti Gallery, Galați, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/68.jpg', true, 1) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/68.jpg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/68.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0839-copy-2.jpg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0839-copy-2.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0841.jpg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0841.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/post-10.06.22-2.jpg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/post-10.06.22-2.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0842.jpg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/dsc_0842.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/52.jpg', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/52.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/1.jpg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/assignment-of-identity-receivables/1.jpg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select 'b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f', '10-17.06.2022, Serfioti Gallery, Galați, Romania', '10-17.06.2022, Serfioti Gallery, Galați, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='b4a4fb7c-959c-5cfe-bba4-2ef26a17f32f' and ev.title_en='10-17.06.2022, Serfioti Gallery, Galați, Romania');
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('26d9b531-18b7-565c-a751-739fac1d5d5c', 'forget-me-not', 'Forget-Me-Not', 'Floare de nu-mă-uita', 'Duo-exhibition', 'Duo-exhibition', 'Gardens have always functioned as spaces of refuge, where inward reflection is deepened by the patience and tranquility of nature, as human presence is enveloped by the eternal beauty of vegetal forms.The exhibitionForget-Me-Notevokes a horizon of memory—of enduring bonds woven into the fabric of existence—interpreted through two distinct chromatic approaches by artists Andreea Gabriela Tudor and Lavinia Maria Oniciuc.

Fragile petals caress our skin, awakening within each of us a long-faded memory, a brief moment of respite in which our dearest experiences may be lived again. Like the shifting chromatic instances of the forget-me-not flower, the figures depicted by the two artists mirror, at varying intensities, subtle messages that create a dialogue between the echoes of our inner states and the emotions drawn viscerally from the soul. In this context, artistGabriela Tudorportrays figures imprisoned within amemento moridimension, the ephemerality of life sheltered within a corporeal vault that conceals a silent messenger of memories that never fade. The reverberation of the forget-me-not also extends to the portraits created by artistLavinia Oniciuc. Stepping timidly out of the dusk-laden gardens, the faces are (il)luminated by the promise of an idealized future, while the play of shadows awaits the unravelling of true human nature.

What does it mean to wither gradually within an impermanent reality, in the hope that one might reconcile the fragility and the power of memory? The exhibition—this sanctuary of the soul—awakens profound sentiments which, much like the forget-me-not flower, refuse to vanish, remaining vivid along the invisible thread of time.', 'Gardens have always functioned as spaces of refuge, where inward reflection is deepened by the patience and tranquility of nature, as human presence is enveloped by the eternal beauty of vegetal forms.The exhibitionForget-Me-Notevokes a horizon of memory—of enduring bonds woven into the fabric of existence—interpreted through two distinct chromatic approaches by artists Andreea Gabriela Tudor and Lavinia Maria Oniciuc.

Fragile petals caress our skin, awakening within each of us a long-faded memory, a brief moment of respite in which our dearest experiences may be lived again. Like the shifting chromatic instances of the forget-me-not flower, the figures depicted by the two artists mirror, at varying intensities, subtle messages that create a dialogue between the echoes of our inner states and the emotions drawn viscerally from the soul. In this context, artistGabriela Tudorportrays figures imprisoned within amemento moridimension, the ephemerality of life sheltered within a corporeal vault that conceals a silent messenger of memories that never fade. The reverberation of the forget-me-not also extends to the portraits created by artistLavinia Oniciuc. Stepping timidly out of the dusk-laden gardens, the faces are (il)luminated by the promise of an idealized future, while the play of shadows awaits the unravelling of true human nature.

What does it mean to wither gradually within an impermanent reality, in the hope that one might reconcile the fragility and the power of memory? The exhibition—this sanctuary of the soul—awakens profound sentiments which, much like the forget-me-not flower, refuse to vanish, remaining vivid along the invisible thread of time.', null, null, '5-30.08.2025,Elite Art Gallery, Bucharest, Romania', '5-30.08.2025,Elite Art Gallery, Bucharest, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-27.jpg', true, 2) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-27.jpg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-27.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-3.jpg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-3.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-49.jpg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-49.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-92.jpg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-92.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-2-2.jpg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-2-2.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/image0-1-1.jpeg', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/image0-1-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-17.jpg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-17.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-26.jpg', 7 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-26.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-22.jpg', 8 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-22.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-2-1.jpg', 9 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-2-1.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-6.jpg', 10 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-6.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-133.jpg', 11 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-133.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-24.jpg', 12 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/forget-me-not/foto-anca-arambasa-24.jpg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '26d9b531-18b7-565c-a751-739fac1d5d5c', '5-30.08.2025,Elite Art Gallery, Bucharest, Romania', '5-30.08.2025,Elite Art Gallery, Bucharest, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='26d9b531-18b7-565c-a751-739fac1d5d5c' and ev.title_en='5-30.08.2025,Elite Art Gallery, Bucharest, Romania');
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('02b40153-bd43-504e-a3f2-e5f2e7058262', 'pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv', 'Pigments of Affective Contact', 'Pigmenți de contact afectiv', 'Itinerant group exhibition', 'Itinerant group exhibition', 'The exhibitionPigments of Affective Contactbrings together four women artists who employ the body—their own or that of the other—as a territory for exploring emotion, memory, and vulnerability. In their works, skin becomes a site where color merges with memory, and the artistic act is transformed into a gesture of tenderness. Color, or pigment, functions as an extension of the human skin—an imprint of emotion that reaches the viewer through layers of sensitivity. Thus, the body no longer appears as a mere object to be looked at, but as an affective landscape in which the boundaries between the visible and the invisible are continuously redefined.

In a world of (over)accelerated interactions, it may not be the act of looking that truly matters, but rather the manner in which we draw near. To look affectively means not to seek a rational meaning within the image, but a sensation. It means allowing oneself to be touched by color, permitting pigment to move beyond vision and reach inward. Within the universe proposed by the artists, red becomes intensity and presence; yellow carries the light of a memory that still breathes; blue is the locus of silence; and violet projects a shadow that touches without causing pain. Thus, color—this omnipresent protagonist in the artists’ works—invites us to step into a space shaped by fragility, longing, absence, and proximity

Diana Păunescuopens this narrative with an incandescent painterly language. In her blazing reds, seemingly subjected to the conditions of a camera obscura, fragments of the body become a living substance, bearing the weight of unarticulated emotion.Georgiana-Geanina Susanuinvestigates the fragility and purity of the human being under the influence of environment and social pressures. Her figures render the tension between inner freedom and external constraint. By contrast, forCristiana-Emanuela Tărbuc, each brushstroke appears as a confessional gesture—an attempt to capture the light pulsing beneath the skin. Her bodies dissolve into light, as if molded from memory. Finally, dominated by cool tonalities, the works ofAndreea-Gabriela Tudorbring forth a sense of inner calm. Her figures oscillate between gesture and thought and, rendered in an almost oneiric manner, seem suspended within a state of temporal uncertainty.', 'The exhibitionPigments of Affective Contactbrings together four women artists who employ the body—their own or that of the other—as a territory for exploring emotion, memory, and vulnerability. In their works, skin becomes a site where color merges with memory, and the artistic act is transformed into a gesture of tenderness. Color, or pigment, functions as an extension of the human skin—an imprint of emotion that reaches the viewer through layers of sensitivity. Thus, the body no longer appears as a mere object to be looked at, but as an affective landscape in which the boundaries between the visible and the invisible are continuously redefined.

In a world of (over)accelerated interactions, it may not be the act of looking that truly matters, but rather the manner in which we draw near. To look affectively means not to seek a rational meaning within the image, but a sensation. It means allowing oneself to be touched by color, permitting pigment to move beyond vision and reach inward. Within the universe proposed by the artists, red becomes intensity and presence; yellow carries the light of a memory that still breathes; blue is the locus of silence; and violet projects a shadow that touches without causing pain. Thus, color—this omnipresent protagonist in the artists’ works—invites us to step into a space shaped by fragility, longing, absence, and proximity

Diana Păunescuopens this narrative with an incandescent painterly language. In her blazing reds, seemingly subjected to the conditions of a camera obscura, fragments of the body become a living substance, bearing the weight of unarticulated emotion.Georgiana-Geanina Susanuinvestigates the fragility and purity of the human being under the influence of environment and social pressures. Her figures render the tension between inner freedom and external constraint. By contrast, forCristiana-Emanuela Tărbuc, each brushstroke appears as a confessional gesture—an attempt to capture the light pulsing beneath the skin. Her bodies dissolve into light, as if molded from memory. Finally, dominated by cool tonalities, the works ofAndreea-Gabriela Tudorbring forth a sense of inner calm. Her figures oscillate between gesture and thought and, rendered in an almost oneiric manner, seem suspended within a state of temporal uncertainty.', '2025-11-11', '2025-12-05', '11.11-5.12.2025, Elite Art Gallery, Bucharest, Romania', '11.11-5.12.2025, Elite Art Gallery, Bucharest, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-4-1.jpeg', true, 3) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-4-1.jpeg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-4-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-2-1.jpeg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-2-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-6-1.jpeg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-6-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-1-1.jpeg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-1-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-3-1.jpeg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-3-1.jpeg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/cover-820x360-v1-2.png', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/cover-820x360-v1-2.png');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-5-1.jpeg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/pigments-of-affective-contact-ro-pigmenti-de-contact-afectiv/Installation-View-5-1.jpeg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '02b40153-bd43-504e-a3f2-e5f2e7058262', '11.11-5.12.2025, Elite Art Gallery, Bucharest, Romania', '11.11-5.12.2025, Elite Art Gallery, Bucharest, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='02b40153-bd43-504e-a3f2-e5f2e7058262' and ev.title_en='11.11-5.12.2025, Elite Art Gallery, Bucharest, Romania');
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('8e04b2fb-58ec-5604-b031-157d81647301', 'the-gift-of-vision', 'The Gift of Vision', 'Darul vederii', 'Itinerant group exhibition', 'Itinerant group exhibition', 'The exhibition’s theme is the centrality of vision—understood both in its common sense of visual perception and in its more specific meaning of attention and discernment—for the act of painting and for the life of the spirit alike. Though far from new, the theme is nevertheless inexhaustible. It is continually renewed and diversified in conjunction with the sensibility of each of the four artists, while simultaneously offering a ground for encounter and dialogue. The exhibition presents four distinct perspectives on nature, four different ways of apprehending and interpreting the material reality of the world.

ForAndreea Gabriela Tudor, nature becomes a theatre of memory, inevitably marked by human presence and by the subjective significations attached to it. At the opposite pole,Raluca Spătaru Iancu’spainting seeks to preserve the spontaneous, immediate feeling before the motif, as if the objects of contemplation were being encountered for the very first time, as if the labour of representation were to begin, each time, from a zero point of absolute ingenuousness.Sorin Scurtulescu’sflowers reveal themselves to the gaze in their paradisiacal, luxuriant splendour, whose expression is decisively linked to the nature of the pictorial material, to luminosity and preciousness. Inclined toward synthesis,Ciprian Bodeacarries out a progressive schematization of the “architecture” of iris flowers, from which he extracts an autonomous structure endowed with its own expressive and ordering valences, positioned at the threshold between the descriptive and the non-representational. Each proposition offers an opportunity to expand the realm of experience, a lived discovery under the arc of the joy of seeing and of painting.

Andreea Gabriela Tudor (b. 2001, Brăila), Raluca Spătaru Iancu (b. 1977, Brăila), Sorin Scurtulescu (b. 1979, Timișoara), and Ciprian Bodea (b. 1979, Cugir)are among the most renowned contemporary Romanian artists, authors of numerous exhibitions hosted in museums, galleries, and cultural institutions in Romania and abroad.

Sorin Scurtulescu and Ciprian Bodeaare founding members of one of the most relevant and influential artistic groups active on the current visual arts scene:Grupul Noima.', 'The exhibition’s theme is the centrality of vision—understood both in its common sense of visual perception and in its more specific meaning of attention and discernment—for the act of painting and for the life of the spirit alike. Though far from new, the theme is nevertheless inexhaustible. It is continually renewed and diversified in conjunction with the sensibility of each of the four artists, while simultaneously offering a ground for encounter and dialogue. The exhibition presents four distinct perspectives on nature, four different ways of apprehending and interpreting the material reality of the world.

ForAndreea Gabriela Tudor, nature becomes a theatre of memory, inevitably marked by human presence and by the subjective significations attached to it. At the opposite pole,Raluca Spătaru Iancu’spainting seeks to preserve the spontaneous, immediate feeling before the motif, as if the objects of contemplation were being encountered for the very first time, as if the labour of representation were to begin, each time, from a zero point of absolute ingenuousness.Sorin Scurtulescu’sflowers reveal themselves to the gaze in their paradisiacal, luxuriant splendour, whose expression is decisively linked to the nature of the pictorial material, to luminosity and preciousness. Inclined toward synthesis,Ciprian Bodeacarries out a progressive schematization of the “architecture” of iris flowers, from which he extracts an autonomous structure endowed with its own expressive and ordering valences, positioned at the threshold between the descriptive and the non-representational. Each proposition offers an opportunity to expand the realm of experience, a lived discovery under the arc of the joy of seeing and of painting.

Andreea Gabriela Tudor (b. 2001, Brăila), Raluca Spătaru Iancu (b. 1977, Brăila), Sorin Scurtulescu (b. 1979, Timișoara), and Ciprian Bodea (b. 1979, Cugir)are among the most renowned contemporary Romanian artists, authors of numerous exhibitions hosted in museums, galleries, and cultural institutions in Romania and abroad.

Sorin Scurtulescu and Ciprian Bodeaare founding members of one of the most relevant and influential artistic groups active on the current visual arts scene:Grupul Noima.', null, null, '04-26.10.2025, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', '04-26.10.2025, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/6.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', true, 4) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/6.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/6.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/darul-vederii_muzeul-brailei_2025_net.jpg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/darul-vederii_muzeul-brailei_2025_net.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/5.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/5.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a6305.jpg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a6305.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/8.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/8.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/13.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/13.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/4.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/4.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a6005.jpg', 7 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a6005.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/10.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 8 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/10.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a5943.jpg', 9 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a5943.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/afis-galati-final.jpg', 10 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/afis-galati-final.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9522-1.jpg', 11 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9522-1.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9800.jpg', 12 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9800.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9569.jpg', 13 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/x6a9569.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/1.-installation-view_darul-vederii_muzeul-brailei_2025.jpg', 14 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/the-gift-of-vision/1.-installation-view_darul-vederii_muzeul-brailei_2025.jpg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', '04-26.10.2025, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', '04-26.10.2025, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and ev.title_en='04-26.10.2025, “Gheorghe Naum” Gallery, Brăila Museum “Carol I”, Brăila, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '8e04b2fb-58ec-5604-b031-157d81647301', '01-23.11.2025, Casa Artelor, Galați, Romania', '01-23.11.2025, Casa Artelor, Galați, Romania', 1 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='8e04b2fb-58ec-5604-b031-157d81647301' and ev.title_en='01-23.11.2025, Casa Artelor, Galați, Romania');
insert into public.exhibitions (id, slug, title_en, title_ro, subtitle_en, subtitle_ro, overview_en, overview_ro, start_date, end_date, venue_en, venue_ro, poster_url, published, sort_order) values ('46ef6615-cfae-535b-8e28-3feb2045bf9e', 'atelier', 'Atelier', 'Atelier', 'Itinerant group exhibition', 'Itinerant group exhibition', 'The exhibition project promotes academic studies in the field of visual arts, illustrating the effort, inspiration, and creativity of young master’s students as an integral part of contemporary artists’ lives, reflected in their engagement with diverse artistic styles and techniques in pursuit of professional success.

3. Brăila (Muzeul Brăilei „Carol I”,Obiectiv – Vocea Brăilei,Monitorul de Brăila)', 'The exhibition project promotes academic studies in the field of visual arts, illustrating the effort, inspiration, and creativity of young master’s students as an integral part of contemporary artists’ lives, reflected in their engagement with diverse artistic styles and techniques in pursuit of professional success.

3. Brăila (Muzeul Brăilei „Carol I”,Obiectiv – Vocea Brăilei,Monitorul de Brăila)', null, null, '03-30.05.2023, Casa Artelor, Galați, Romania', '03-30.05.2023, Casa Artelor, Galați, Romania', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2584.jpg', true, 5) on conflict (slug) do update set title_en=excluded.title_en, title_ro=excluded.title_ro, subtitle_en=excluded.subtitle_en, poster_url=excluded.poster_url, venue_en=excluded.venue_en, start_date=excluded.start_date, end_date=excluded.end_date, published=true;
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2584.jpg', 0 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2584.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2590.jpg', 1 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2590.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-VASLUI-724x1024.jpg', 2 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-VASLUI-724x1024.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-GALATI.jpg', 3 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-GALATI.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-BRAILA-731x1024.jpg', 4 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-BRAILA-731x1024.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2669.jpg', 5 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/DSCF2669.jpg');
insert into public.exhibition_gallery_images (exhibition_id, image_url, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-BARLAD-724x1024.jpg', 6 where not exists (select 1 from public.exhibition_gallery_images g where g.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and g.image_url='https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/exhibitions/atelier/ATELIER-2023-BARLAD-724x1024.jpg');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', '03-30.05.2023, Casa Artelor, Galați, Romania', '03-30.05.2023, Casa Artelor, Galați, Romania', 0 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and ev.title_en='03-30.05.2023, Casa Artelor, Galați, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', '09.06-03.07.2023, “Vasile Pârvan” Museum, Bârlad, Romania', '09.06-03.07.2023, “Vasile Pârvan” Museum, Bârlad, Romania', 1 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and ev.title_en='09.06-03.07.2023, “Vasile Pârvan” Museum, Bârlad, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', '04-29.10.2023, “Carol I” Museum, Brăila, Romania', '04-29.10.2023, “Carol I” Museum, Brăila, Romania', 2 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and ev.title_en='04-29.10.2023, “Carol I” Museum, Brăila, Romania');
insert into public.exhibition_venues (exhibition_id, title_en, title_ro, sort_order) select '46ef6615-cfae-535b-8e28-3feb2045bf9e', '06-28.03.2024, “Ştefan cel Mare” County Museum, Vaslui, Romania', '06-28.03.2024, “Ştefan cel Mare” County Museum, Vaslui, Romania', 3 where not exists (select 1 from public.exhibition_venues ev where ev.exhibition_id='46ef6615-cfae-535b-8e28-3feb2045bf9e' and ev.title_en='06-28.03.2024, “Ştefan cel Mare” County Museum, Vaslui, Romania');

-- EVENTS (from art-events index page)
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('ef8faf0d-3ad3-5e77-b0d2-512818d6507e', 'This Space Does Not Exist', 'Acest spațiu nu există', 'itinerant exhibition
2024-2025
2022', 'itinerant exhibition
2024-2025
2022', '2024-01-01', 'itinerant exhibition', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/acest-spatiu-nu-exista.jpg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('ef8faf0d-3ad3-5e77-b0d2-512818d6507e', 'This Space Does Not Exist', 'Acest spațiu nu există', 'itinerant exhibition
2024-2025', 'itinerant exhibition
2024-2025', '2024-01-01', 'itinerant exhibition', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/acest-spatiu-nu-exista.jpg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('ef8faf0d-3ad3-5e77-b0d2-512818d6507e', 'This Space Does Not Exist', 'Acest spațiu nu există', 'itinerant exhibition
2024-2025', 'itinerant exhibition
2024-2025', '2024-01-01', 'itinerant exhibition', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('8fd2949e-99ce-5d2e-87f3-8a855c9f50c1', 'Assignment of Identity Receivables', 'Cesiune de creanțe identitare', '2022', '2022', '2022-01-01', '2022', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/post-10.06.22-1.jpg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('8fd2949e-99ce-5d2e-87f3-8a855c9f50c1', 'Assignment of Identity Receivables', 'Cesiune de creanțe identitare', '2022', '2022', '2022-01-01', '2022', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('d3a832d2-0bce-53c6-bf06-896d49b81249', 'ROGVAIV pe cerul inimii', 'ROGVAIV pe cerul inimii', '2026
2025
itinerant exhibition
2025
duo-exhibition with Lavinia Maria Oniciuc
2024
itinerant exhibition
2023-2024', '2026
2025
itinerant exhibition
2025
duo-exhibition with Lavinia Maria Oniciuc
2024
itinerant exhibition
2023-2024', '2026-01-01', '2026', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/fb-page-1200x628-v1-2.png') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('d3a832d2-0bce-53c6-bf06-896d49b81249', 'ROGVAIV pe cerul inimii', 'ROGVAIV pe cerul inimii', '2026', '2026', '2026-01-01', '2026', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/fb-page-1200x628-v1-2.png') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('d3a832d2-0bce-53c6-bf06-896d49b81249', 'ROGVAIV pe cerul inimii', 'ROGVAIV pe cerul inimii', '2026', '2026', '2026-01-01', '2026', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('6cd229e9-dd3b-5ac8-8aac-4ad7ff4f2b43', 'Pigments of Affective Contact', 'Pigmenți de contact afectiv', '2025', '2025', '2025-01-01', '2025', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/fb-page-1200x628-v1-2.png') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('6cd229e9-dd3b-5ac8-8aac-4ad7ff4f2b43', 'Pigments of Affective Contact', 'Pigmenți de contact afectiv', '2025', '2025', '2025-01-01', '2025', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('7f6afe72-22fd-52b2-a0b3-cd6f86af4988', 'The Gift of Vision', 'Darul vederii', 'itinerant exhibition
2025', 'itinerant exhibition
2025', '2025-01-01', 'itinerant exhibition', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/postare-1080-x-1080-px-2-1.jpeg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('7f6afe72-22fd-52b2-a0b3-cd6f86af4988', 'The Gift of Vision', 'Darul vederii', 'itinerant exhibition
2025', 'itinerant exhibition
2025', '2025-01-01', 'itinerant exhibition', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('2a5c186b-39cf-50d2-ae0b-eaeb7e30b311', 'Forget-Me-Not', 'Floare de nu-mă-uita', 'duo-exhibition with Lavinia Maria Oniciuc
2024', 'duo-exhibition with Lavinia Maria Oniciuc
2024', '2024-01-01', 'duo-exhibition with Lavinia Maria Oniciuc', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/image0-1.jpeg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('2a5c186b-39cf-50d2-ae0b-eaeb7e30b311', 'Forget-Me-Not', 'Floare de nu-mă-uita', 'duo-exhibition with Lavinia Maria Oniciuc
2024', 'duo-exhibition with Lavinia Maria Oniciuc
2024', '2024-01-01', 'duo-exhibition with Lavinia Maria Oniciuc', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('7724a74e-78b5-58cf-8530-a8a9602a9fe7', 'Atelier', 'Atelier', 'itinerant exhibition
2023-2024', 'itinerant exhibition
2023-2024', '2023-01-01', 'itinerant exhibition', 'https://rptwowkkejecvvbfsgkt.supabase.co/storage/v1/object/public/artwork-images/wp-import/events/art_1.jpg') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;
insert into public.events (id, title_en, title_ro, body_en, body_ro, event_date, location, image_url) values ('7724a74e-78b5-58cf-8530-a8a9602a9fe7', 'Atelier', 'Atelier', 'itinerant exhibition
2023-2024', 'itinerant exhibition
2023-2024', '2023-01-01', 'itinerant exhibition', '') on conflict (id) do update set title_en=excluded.title_en, body_en=excluded.body_en, image_url=excluded.image_url;

commit;