/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitionsIndexRouteImport } from './routes/exhibitions.index'
import { Route as ExhibitionsSlugRouteImport } from './routes/exhibitions.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsIndexRoute = ExhibitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const ExhibitionsSlugRoute = ExhibitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExhibitionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/exhibitions': typeof ExhibitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/shop': typeof ShopRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/exhibitions/': typeof ExhibitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/exhibitions'
    | '/login'
    | '/projects'
    | '/shop'
    | '/exhibitions/$slug'
    | '/exhibitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/login'
    | '/projects'
    | '/shop'
    | '/exhibitions/$slug'
    | '/exhibitions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/exhibitions'
    | '/login'
    | '/projects'
    | '/shop'
    | '/exhibitions/$slug'
    | '/exhibitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EventsRoute: typeof EventsRoute
  ExhibitionsRoute: typeof ExhibitionsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/': {
      id: '/exhibitions/'
      path: '/'
      fullPath: '/exhibitions/'
      preLoaderRoute: typeof ExhibitionsIndexRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/exhibitions/$slug': {
      id: '/exhibitions/$slug'
      path: '/$slug'
      fullPath: '/exhibitions/$slug'
      preLoaderRoute: typeof ExhibitionsSlugRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
  }
}

interface ExhibitionsRouteChildren {
  ExhibitionsSlugRoute: typeof ExhibitionsSlugRoute
  ExhibitionsIndexRoute: typeof ExhibitionsIndexRoute
}

const ExhibitionsRouteChildren: ExhibitionsRouteChildren = {
  ExhibitionsSlugRoute: ExhibitionsSlugRoute,
  ExhibitionsIndexRoute: ExhibitionsIndexRoute,
}

const ExhibitionsRouteWithChildren = ExhibitionsRoute._addFileChildren(
  ExhibitionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EventsRoute: EventsRoute,
  ExhibitionsRoute: ExhibitionsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
